const express = require('express')
const router = express.Router()
const getController = require('../controllers/get.controllers')
const getControllerAvis = require('../controllers/get.controllers.reviews')
const getControllerAvisId = require('../controllers/get.controllers.reviews.id')
const postController = require('../controllers/post.controllers')
const postControllerRegister = require('../controllers/post.controllers.register')
const postControllerLogin = require('../controllers/post.controllers.login')
const postControllerForgotPassword = require('../controllers/post.controllers.forgot-password')
const postControllerResetPassword = require('../controllers/post.controllers.reset-password')
const putController = require('../controllers/put.controllers')
const deleteController = require('../controllers/delete.controllers')
const getMiddleware = require('../middleware/get.middleware')
const getMiddlewareReviews = require('../middleware/get.middleware.reviews')

router.get('/',getMiddleware, getController)
router.get('/avis', getMiddlewareReviews, getControllerAvis)
router.get('/avis/:id', getControllerAvisId)
router.post('/add/avis', postController)
router.put('/autoriser/avis/:id', putController)
router.delete('/avis/:id', deleteController)
router.post('/register', postControllerRegister)
router.post('/login', postControllerLogin)
router.post('/change-password', putController)
router.post('/forgot-password', postControllerForgotPassword)
router.post('/reset-password', postControllerResetPassword)

module.exports = router